/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Admin: () => import('#controllers/admin_controller'),
  AdminMaterialy: () => import('#controllers/admin_materialy_controller'),
  AdminTasks: () => import('#controllers/admin_tasks_controller'),
  ListaZadan: () => import('#controllers/lista_zadan_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Sciezka: () => import('#controllers/sciezka_controller'),
  Session: () => import('#controllers/session_controller'),
}
