/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuditLogSchema extends BaseModel {
  static $columns = ['akcja', 'createdAt', 'id', 'idObiektu', 'idUzytkownika', 'opis', 'typObiektu', 'uzytkownik', 'zmiany'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare akcja: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idObiektu: number | null
  @column()
  declare idUzytkownika: number | null
  @column()
  declare opis: string
  @column()
  declare typObiektu: string
  @column()
  declare uzytkownik: string
  @column()
  declare zmiany: any | null
}

export class ListaZadanSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'hint', 'idAutora', 'idPoziomuTrudnosci', 'idZadania', 'kodCpp', 'kodPython', 'linkDodatkoweMaterialy', 'linkOmowienieVid', 'linkTresc', 'linkWyslij', 'linkZrodlo', 'nazwa', 'omowienieText', 'published', 'tagi', 'updatedAt', 'zrodlo'] as const
  $columns = ListaZadanSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare hint: string | null
  @column()
  declare idAutora: number | null
  @column()
  declare idPoziomuTrudnosci: number | null
  @column({ isPrimary: true })
  declare idZadania: number
  @column()
  declare kodCpp: string | null
  @column()
  declare kodPython: string | null
  @column()
  declare linkDodatkoweMaterialy: string | null
  @column()
  declare linkOmowienieVid: string | null
  @column()
  declare linkTresc: string
  @column()
  declare linkWyslij: string | null
  @column()
  declare linkZrodlo: string | null
  @column()
  declare nazwa: string
  @column()
  declare omowienieText: string | null
  @column()
  declare published: boolean
  @column()
  declare tagi: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare zrodlo: string
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'token', 'userId'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
  @column()
  declare userId: number
}

export class PoziomySchema extends BaseModel {
  static $columns = ['createdAt', 'customHtml', 'deletedAt', 'idPoziomu', 'nazwa', 'poboczny', 'position', 'updatedAt'] as const
  $columns = PoziomySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customHtml: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare idPoziomu: number
  @column()
  declare nazwa: string
  @column()
  declare poboczny: boolean
  @column()
  declare position: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PoziomyTrudnosciSchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'idPoziomuTrudnosci', 'position', 'rozwiniecie', 'skrot', 'updatedAt'] as const
  $columns = PoziomyTrudnosciSchema.$columns
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare idPoziomuTrudnosci: number
  @column()
  declare position: number
  @column()
  declare rozwiniecie: string
  @column()
  declare skrot: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TagiSchema extends BaseModel {
  static $columns = ['idTagu', 'nazwa'] as const
  $columns = TagiSchema.$columns
  @column({ isPrimary: true })
  declare idTagu: number
  @column()
  declare nazwa: string
}

export class TematySchema extends BaseModel {
  static $columns = ['createdAt', 'customHtml', 'deletedAt', 'idAutora', 'idPoziomu', 'idTematu', 'krotkiOpis', 'linkYt', 'nazwa', 'position', 'published', 'updatedAt', 'zadaniaCwiczeniowe', 'zadaniaDodatkowe', 'zadaniaNaPomysl', 'zadaniaTreningowe', 'zewnetrzneMaterialy', 'zewnetrzneMaterialyOpisy'] as const
  $columns = TematySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customHtml: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare idAutora: number | null
  @column()
  declare idPoziomu: number | null
  @column({ isPrimary: true })
  declare idTematu: number
  @column()
  declare krotkiOpis: string | null
  @column()
  declare linkYt: string | null
  @column()
  declare nazwa: string
  @column()
  declare position: number
  @column()
  declare published: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare zadaniaCwiczeniowe: any | null
  @column()
  declare zadaniaDodatkowe: any | null
  @column()
  declare zadaniaNaPomysl: any | null
  @column()
  declare zadaniaTreningowe: any | null
  @column()
  declare zewnetrzneMaterialy: any | null
  @column()
  declare zewnetrzneMaterialyOpisy: any | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
